"""init

Revision ID: 18a245d9547d
Revises: 
Create Date: 2023-10-25 06:39:19.467048

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '18a245d9547d'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exchangeratess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('currency_name', sa.String(), nullable=False),
    sa.Column('currency_iso_code', sa.String(), nullable=False),
    sa.Column('rates', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('currency_iso_code')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('exchangeratess')
    # ### end Alembic commands ###
